# Generated by Django 2.2 on 2020-10-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MadlibFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjective', models.CharField(max_length=25)),
                ('verb', models.CharField(max_length=25)),
                ('adjective2', models.CharField(max_length=25)),
                ('adverb', models.CharField(max_length=25)),
                ('place', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('animal', models.CharField(max_length=25)),
            ],
        ),
    ]
